name: Build and Push Docker Image to GHCR

on:
  push:  # Triggers the workflow on push events to the main branch
    branches:
      - main
  schedule:  # Optional: Schedule the job to run daily
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Get latest autobrr release version
      id: get_release
      run: |
        latest_version=$(curl -s https://api.github.com/repos/autobrr/autobrr/releases/latest | jq -r .tag_name)
        echo "latest_version=$latest_version" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . -t ghcr.io/${{ github.repository }}/autobrr-qbitrace:${{ env.latest_version }}

    - name: Push to GHCR
      run: docker push ghcr.io/${{ github.repository }}/autobrr-qbitrace:${{ env.latest_version }}

    - name: Send Gotify Notification
      run: |
        curl -X POST \
        -H 'Content-type: application/json' \
        -H "waf-bypass: ${{ secrets.WAF_BYPASS }}" \
        -F "title=New Docker Image Pushed" \
        -F "message=A new Docker image for autobrr-qbitrace version ${latest_version} has been pushed to GHCR." \
        ${{ secrets.GOTIFY_WEBHOOK_URL }}
