name: Docker Build and Push

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new base image
        id: check-image
        run: |
          # Replace 'base-image:tag' with your actual base image and tag
          LATEST_DIGEST=$(docker pull base-image:tag 2>&1 | grep Digest | cut -d' ' -f2)
          echo "LATEST_DIGEST=$LATEST_DIGEST" >> $GITHUB_OUTPUT
          if [ -f .last_built_digest ]; then
            LAST_BUILT_DIGEST=$(cat .last_built_digest)
            if [ "$LATEST_DIGEST" != "$LAST_BUILT_DIGEST" ]; then
              echo "new_version=true" >> $GITHUB_OUTPUT
            else
              echo "new_version=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "new_version=true" >> $GITHUB_OUTPUT
          fi

      - name: Checkout code
        if: steps.check-image.outputs.new_version == 'true'
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        if: steps.check-image.outputs.new_version == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: steps.check-image.outputs.new_version == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.check-image.outputs.new_version == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-image:latest

      - name: Update last built digest
        if: steps.check-image.outputs.new_version == 'true'
        run: |
          echo "${{ steps.check-image.outputs.LATEST_DIGEST }}" > .last_built_digest
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .last_built_digest
          git commit -m "Update last built digest"
          git push
